plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
markdown: GFM
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: KoboldKare Wiki
description: A temporary wiki for a game KoboldKare. May or may not contain outdated information
remote_theme: pages-themes/minimal